version: '3.8'

services:
  frontend:
    image: my-nextjs-app:latest 
    ports:
      - "3000:3000"
    depends_on:
      - backend  

  backend:
    image: api:latest
    ports:
      - "8000:80" 
    depends_on:
      - database  

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: